"""add plans table and plan_id to workout_queue

Revision ID: b2321a8b7f43
Revises: 1dff03560e0c
Create Date: 2026-04-04 16:54:33.570072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2321a8b7f43'
down_revision: Union[str, None] = '1dff03560e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('activity_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plans_activity_type'), 'plans', ['activity_type'], unique=False)
    op.create_index(op.f('ix_plans_status'), 'plans', ['status'], unique=False)
    op.add_column('workout_queue', sa.Column('plan_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workout_queue_plan_id'), 'workout_queue', ['plan_id'], unique=False)
    op.create_foreign_key(None, 'workout_queue', 'plans', ['plan_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workout_queue', type_='foreignkey')
    op.drop_index(op.f('ix_workout_queue_plan_id'), table_name='workout_queue')
    op.drop_column('workout_queue', 'plan_id')
    op.drop_index(op.f('ix_plans_status'), table_name='plans')
    op.drop_index(op.f('ix_plans_activity_type'), table_name='plans')
    op.drop_table('plans')
    # ### end Alembic commands ###
