"""add plan_workout_id to workout

Revision ID: 1dff03560e0c
Revises: 11b45ca4a422
Create Date: 2026-04-04 16:24:47.456209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dff03560e0c'
down_revision: Union[str, None] = '11b45ca4a422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workout', sa.Column('plan_workout_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_workout_plan_workout_id'), 'workout', ['plan_workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_plan_workout_id'), table_name='workout')
    op.drop_column('workout', 'plan_workout_id')
    # ### end Alembic commands ###
